apiVersion: v2
appVersion: 0.211.0
description: Helm chart for EVCC (evcc.io)
home: https://evcc.io/
icon: https://jitsehijlkema.github.io/evcc-chart/evcc-logo.png
keywords:
- evcc
- charging
- ev
name: evcc
type: application
version: 1.0.30
