{{- if and .Values.persistence.enabled .Values.persistence.backup.enabled (not .Values.persistence.backup.s3.existingSecret) (or .Values.persistence.backup.s3.accessKeyId .Values.persistence.backup.s3.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evcc.fullname" . }}-litestream
  labels:
    {{- include "evcc.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.persistence.backup.s3.accessKeyId }}
  access-key-id: {{ .Values.persistence.backup.s3.accessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.persistence.backup.s3.secretAccessKey }}
  secret-access-key: {{ .Values.persistence.backup.s3.secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}

